armor_override:
  armor_reduction_cap: 0.5

shield_nerf:
  default_damage_multiplier: 2.0
  axe_damage_multiplier: 5.0
  damage_after_blocking_multiplier: 0.5

weapon_override:
  cooldown_threshold: 0.5